org.gradle.jvmargs=-Xmx1G

loom.platform=neoforge

ffapi_modules=fabric-api-base,fabric-networking-api-v1

minecraft_version_range=[1.21.5,)
neoforge_version_range=[21.5,)
fml_version_range=[4,)

mod_id=mafglib
mod_license=LGPL-3.0
mod_credits=masa
mod_authors=TexTrue, ThinkingStudio
mod_description=MaLiLib unofficial (Neo)Forge port. Library mod for the (Neo)Forge port of masa's mods.
mod_link=https://github.com/ThinkingStudios/MaLiLib-Forge