modLoader="javafml"
loaderVersion="${fml_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_link}/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_link}"
logoFile="icon.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="mixins.malilib.json"

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"